### ISSUE TITLE
How do i use it?

### ISSUE THREAD

**Issue by SuperDZ555** [Keheck/MinecraftDatapackCreator#2]
I have no idea how i use it! Pls add a guide!

**Comment by Keheck** [comment]
You have to go to "releases" and download one of the jars.
Then you simply run the jar file. I'll just assume you already got java since you have Minecraft (i hope)

**Comment by Keheck** [comment]
I added a [guide](https://github.com/Keheck/MinecraftDatapackCreator/wiki/How-do-I-start-the-program%3F) now.
